In [1]:
import tensorflow as tf

## 1. Automatic Differentiation with Gradients

In [3]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2
grad = tape.gradient(y, x)

print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


## 2. Custom Training Loops

In [4]:
for epoch in range(10):
    with tf.GradientTape() as tape:
        loss = compute_loss() # your custom loss function
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizaer.apply_gradients(zip(gradients, model.trainable_variables))

NameError: name 'compute_loss' is not defined

## 3. Tensor operations and Broadcasting

In [5]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y = tf.constant([5.0, 6.0])

result = x + y
print(result)

tf.Tensor(
[[ 6.  8.]
 [ 8. 10.]], shape=(2, 2), dtype=float32)


## 4. Efficient data processing with tf.data API

In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.map(lambda x: x * 2)
dataset = dataset.batch(2)

for batch in dataset:
    print(batch)

tf.Tensor([0 2], shape=(2,), dtype=int64)
tf.Tensor([4 6], shape=(2,), dtype=int64)
tf.Tensor([ 8 10], shape=(2,), dtype=int64)
tf.Tensor([12 14], shape=(2,), dtype=int64)
tf.Tensor([16 18], shape=(2,), dtype=int64)


## 5. GPU Acceleration & tf.function Optimization

In [9]:
@tf.function
def fast_function(x):
    return x ** 2 + 3

print(fast_function(tf.constant([2.0, 3.0])))

tf.Tensor([ 7. 12.], shape=(2,), dtype=float32)
