In [1]:
import torch

## 1. Automatic Differentiation with Gradients

In [3]:
x = torch.tensor(3.0, requires_grad = True)

y = x ** 2
y.backward()

print(x.grad)

tensor(6.)


## 2. Custom Training Loops

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(10):
    optimizer.zero_grad()  # Clear gradients
    loss = compute_loss()  # Define custom loss function
    loss.backward()  # Compute gradients
    optimizer.step()  # Update model parameters

NameError: name 'compute_loss' is not defined

## 3. Tensor operations and Broadcasting

In [5]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = torch.tensor([5.0, 6.0])

print(x + y)

tensor([[ 6.,  8.],
        [ 8., 10.]])


## 4. Efficient data processing with tf.data API

In [10]:
from torch.utils.data import DataLoader, TensorDataset

dataset = TensorDataset(torch.arange(10).float())
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

for batch in dataloader:
    print(batch)

[tensor([0., 1.])]
[tensor([2., 3.])]
[tensor([4., 5.])]
[tensor([6., 7.])]
[tensor([8., 9.])]


## 5. GPU Acceleration & tf.function Optimization

In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(tensor)

tensor([1., 2., 3.])


In [13]:
@torch.jit.script
def fast_function(x: torch.Tensor):
    return x ** 2 + 3

print(fast_function(torch.tensor([2.0, 3.0])))

tensor([ 7., 12.])
